### ISSUE TITLE
Ranking Idea

### ISSUE THREAD

**Issue by gootik** [tmaciejewski/see#1]
Something like this could be used for ranking/indexing https://blog.kabir.ml/posts/inside-wade.html

**Comment by tmaciejewski** [comment]
Thanks, I'll take a look. At first I was thinking about this: https://en.wikipedia.org/wiki/Tf%E2%80%93idf

My goal is to recreate the original Google's PageRank.

**Comment by tmaciejewski** [comment]
closing as tf-idf has been implemented
